spring.application.name=demo


#https://albertprofe.dev/springboot/sblab8-3.html#configuring-h2-database-in-spring-boot-with-ddl-auto-generation
# Data source configuration
# we need this configuration because
# spring boot needs the actual data of the database
# to know what db identity we are talking about
# With this data we will be able to connect to

# direction, where does it live
# local, memory, test
# local: linux path
spring.datasource.url=jdbc:h2:/home/albert/MyProjects/SpringProjects/compassMap/db/compassmapdb
# in-memory
#spring.datasource.url=jdbc:h2:mem:testdb
# test
#spring.datasource.url=jdbc:h2:~/test

# we need the driver
spring.datasource.driverClassName=org.h2.Driver
# credentials
spring.datasource.username=albert
spring.datasource.password=1234

# we define the SQL dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# OPTIONAL
# create: Drops and creates the schema at application startup.
#create-drop: Creates the schema at startup and drops it at shutdown.
#update: Updates the schema if necessary (recommended for development).
#validate: Validates the schema but makes no changes.
#none: Disables DDL handling.
spring.jpa.hibernate.ddl-auto=update
# at console ide we want to see the actual queries
# spring boot is sending to the db
spring.jpa.show-sql=true